export default {
	common: {
		Fire: [ '불' ],
		Electric: [ '전기' ],
		Wind: [ '바람' ],
		Poison: [ '독' ],
		Ice: [ '얼음' ],
		Iron: [ '쇠' ],
		Broken: [ '고장난', '고장' ],
		Gamble: [ '도박' ],
		Lock: [ '잠금' ]
	},
	rare: {
		Mine: [ '광산' ],
		Light: [ '빛' ],
		Thorn: [ '가시' ],
		Crack: [ '균열' ],
		Critical: [ '크리티컬' ],
		Energy: [ '에너지' ],
		Sacrifice: [ '제물' ],
		Arrow: [ '활' ],
		RandomGrowth: [ '도박성장', '도성' ]
	},
	epic: {
		Death: [ '죽음' ],
		Teleport: [ '텔레포트', '텔포' ],
		Laser: [ '레이저' ],
		Mimic: [ '적응' ],
		Infect: [ '감염' ],
		ModifiedElectric: [ '개조된전기', '개조전기', '개전' ],
		Absorb: [ '흡수' ],
		MightyWind: [ '강풍' ],
		Switch: [ '스위치' ],
		Gear: [ '기어' ],
		Wave: [ '파동' ],
		Flame: [ '화염' ],
		Healing: [ '회복' ],
		Clone: [ '복제' ],
		CrackedGrowth: [ '고장난성장', '고장성장', '고성' ],
		Rock: [ '돌' ],
		Bounty: [ '현상금' ],
		EmptyGift: [ '빈선물', '선물' ],
	},
	legendary: {
		Nuclear: [ '핵' ],
		Landmine: [ '지뢰' ],
		SandSwamp: [ '모래' ],
		Joker: [ '조커' ],
		HolySword: [ '빛의검', '빛검' ],
		Hell: [ '지옥' ],
		Shield: [ '방패' ],
		Blizzard: [ '눈보라' ],
		Growth: [ '성장' ],
		Summoner: [ '소환' ],
		Solar: [ '태양' ],
		Assassin: [ '암살' ],
		Atomic: [ '원자' ],
		Gun: [ '총' ],
		Typhoon: [ '태풍' ],
		Supplement: [ '양분' ],
		Metastasis: [ '전이' ],
		Time: [ '시간' ],
		Combo: [ '콤보' ],
		Lunar: [ '달' ],
		Flow: [ '흐름' ],
		Star: [ '별' ],
		ix10: [ 'ix10', '해킹' ],
		Silence: [ '침묵' ],
		Royal: [ '로얄' ],
		YinYang: [ '태극' ],
		Scope: [ '조준경' ]
	}
}
